Algoritmo "Soma_Dois"
// Universidade Federal Rural do Semi-Árido - UFERSA
// Algoritmos & Programação
// Descrição   : Soma Dois Números (Soma)
// Autor(a)    : Ea Oficial
// Data atual  : 20/04/2024

Var
Soma, Num1, Num2: inteiro

Inicio
    escreval("Informe o primeiro número:")
    leia(Num1)
    escreval("Informe o segundo número:")
    leia(Num2)

    Soma <- Num1 + Num2

    escreval("O resultado da soma entre ", Num1, " e ", Num2, " foi: ", Soma)

Fimalgoritmo