Algoritmo "Celsius_para_Fahrenheit"
// Universidade Federal Rural do Semi-Árido - UFERSA
// Algoritmos & Programação
// Descrição   : Conversão de Temperatura de Celsius para Fahrenheit
// Autor(a)    : Ea Oficial
// Data atual  : 20/04/2024

Var
    Celsius, Fahrenheit: real

Inicio
    escreval("Informe a temperatura em Celsius:")
    leia(Celsius)

    Fahrenheit <- 9 / 5 * Celsius + 32

    escreval("A temperatura em Fahrenheit é: ", Fahrenheit)

Fimalgoritmo
